# Changes here will be overwritten by Copier.
_commit: 1.4.1
_src_path: gh:mkdocstrings/handler-template
author_email: 7960706+mammothb@users.noreply.github.com
author_fullname: mmb L
author_username: mammothb
copyright_date: '2025'
copyright_holder: mmb L
copyright_holder_email: 7960706+mammothb@users.noreply.github.com
copyright_license: MIT
insiders: false
language: GraphQL
project_description: A GraphQL handler for mkdocstrings.
project_name: mkdocstrings-graphql
python_package_distribution_name: mkdocstrings-graphql
python_package_import_name: graphql
repository_name: mkdocstrings-graphql
repository_namespace: mammothb
repository_provider: github.com

