name: publish
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        run: uv tool run pdm build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
    needs: test-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        run: uv tool run pdm build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
